### ISSUE TITLE
Colab returning error : CUDA out of memory

### ISSUE THREAD

**Issue by alessandro-lion** [microsoft/Bringing-Old-Photos-Back-to-Life#72] opened 2020-12-05 20:26 UTC
I tried to process a png scan from my computer which is about 3900x2700 pixel sized using the Colab. It failed so I tried to use a resized copy of that which is about 1177x814 pixel but there is always the same issue, here the log:

```
Running Stage 1: Overall restoration
initializing the dataloader
model weights loaded
directory of testing image: /photo_restoration/test_images/upload
processing .ipynb_checkpoints
Skipping non-file .ipynb_checkpoints
processing My_scan0001.png
You are using NL + Res
Now you are processing Mamma_scan0001.png
Skip Mamma_scan0001.png due to an error:
CUDA out of memory. Tried to allocate 13.58 GiB (GPU 0; 14.73 GiB total capacity; 1.32 GiB already allocated; 10.21 GiB free; 3.58 GiB reserved in total by PyTorch)
Finish Stage 1 ...


Running Stage 2: Face Detection
Finish Stage 2 ...


Running Stage 3: Face Enhancement
The main GPU is 
0
dataset [FaceTestDataset] of size 0 was created
The size of the latent vector size is [8,8]
Network [SPADEGenerator] was created. Total number of parameters: 92.1 million. To see the architecture, do print(network).
hi :)
Finish Stage 3 ...


Running Stage 4: Blending
Finish Stage 4 ...


All the processing is done. Please check the results.
```

**Comment by SikandAlex** [comment] 2020-12-06 08:14
I had the same issue. You need to go even a wee bit smaller than your resized image.

**Comment by zhangmozhe** [comment] 2021-02-04 06:06
Duplicate of https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/issues/19#issue-711976416

**Closed by zhangmozhe** 2021-02-04 06:06 UTC
