### ISSUE TITLE
Titan x out of memory??

### ISSUE THREAD

**Issue by bwanaaa** [microsoft/Bringing-Old-Photos-Back-to-Life#87] opened 2020-12-15 22:47 UTC
using a titan x pascal (12 gb vram) and an image that is 841 pixels x 100 pixels

gives

```
CUDA out of memory. Tried to allocate 40.00 MiB (GPU 0; 11.91 GiB total capacity; 10.14 GiB already allocated; 9.62 MiB free; 10.28 GiB reserved in total by PyTorch)
Finish Stage 1 ...

```
nvidia-smi gives

Tue Dec 15 18:30:50 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  TITAN X (Pascal)    On   | 00000000:01:00.0  On |                  N/A |
| 23%   40C    P2    57W / 250W |    958MiB / 12193MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1306      G   /usr/lib/xorg/Xorg                            45MiB |
|    0      1352      G   /usr/bin/gnome-shell                          49MiB |
|    0      6929      G   /usr/lib/xorg/Xorg                           569MiB |
|    0      7060      G   /usr/bin/gnome-shell                         290MiB |
+-----------------------------------------------------------------------------+

**Comment by bwanaaa** [comment] 2020-12-15 23:35
even with a ridiculously small image I am getting out of memory error?

**Comment by zhangmozhe** [comment] 2021-02-04 06:09
Duplicate of https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/issues/19#issue-711976416

**Closed by zhangmozhe** 2021-02-04 06:09 UTC
