### ISSUE TITLE
CUDA Out Of Memory. The code is impractical 

### ISSUE THREAD

**Issue by franva** [microsoft/Bringing-Old-Photos-Back-to-Life#86] opened 2020-12-14 22:30 UTC
Hit this issue, my PC config is:

Ubuntu 20.04
NVIDIA RTX 2080 Ti 11GB RAM
64 GB RAM

The resolution of images I'm trying to repair is 1280*720.

I have read the same problem in 3 posts and found people with lower resolutions still have the same issue.
Someone suggests to shrink pic size or use Colab, but it's not practical in my case.

The purpose of this code is to fix pictures to have better look and feel. 
If I have to reduce the resolution of the images, say I have 1280*720 reso and reduced to 640*360 to see its repaired version, then the code defeats its purpose. And a 16GB RAM's GPU is out of reach for many people.

I assume that there should be an approach to reduce the use of GPU RAM, even it slows down the speed of repairing, but for me it's still acceptable.

Thanks in advance for any help.

**Comment by dev-tty** [comment] 2020-12-27 01:34
I'm having the same problem on CPU only, no scratch repair.  I've found only the sample images and very small faded images work.

**Comment by zhangmozhe** [comment] 2021-02-04 05:50
Duplicate of https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/issues/19#issue-711976416

**Closed by zhangmozhe** 2021-02-04 05:50 UTC
