### ISSUE TITLE
Some images just won't process

### ISSUE THREAD

**Issue by gmcbrien** [microsoft/Bringing-Old-Photos-Back-to-Life#111] opened 2021-01-28 16:59 UTC
Some images just won't process at all. For example, https://i.redd.it/40uibawdqtd61.jpg

I am running a local installation, and able to process most jpgs. But, there is a rate of about 1/3 of jpgs that simply won't process. All CPUs on my PC go to 100%.
I have tried re-saving in image editing programs, converting to other formats etc. They simply won't process.

Anybody any idea why this might be...?

**Comment by SikandAlex** [comment] 2021-02-04 01:44
I don't think you're gonna have any luck running this on CPU.

**Comment by zhangmozhe** [comment] 2021-02-04 06:07
Duplicate of https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/issues/19#issue-711976416

**Closed by zhangmozhe** 2021-02-04 06:07 UTC
