### ISSUE TITLE
Image that is 50% the size of test images - CUDA Out of Memory

### ISSUE THREAD

**Issue by SikandAlex** [microsoft/Bringing-Old-Photos-Back-to-Life#114] opened 2021-02-04 02:07 UTC
I have resized my image so many times to see if I can just get Stage 1 to work. No matter what I try it claims it needs an additional 858 MB of data. This doesn't make any sense to me. The test images with scratches are about 600 KB and I uploaded an image that only takes up 250 KB. Still fails. Can we please get this memory issue addressed or at least have some guidance? Seems to me the code is sloppy.

**Comment by zhangmozhe** [comment] 2021-02-04 05:50
Duplicate of https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/issues/19#issue-711976416

**Closed by zhangmozhe** 2021-02-04 05:50 UTC
