### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Davydhh** [microsoft/Bringing-Old-Photos-Back-to-Life#54] opened 2020-11-24 17:28 UTC
With some image throws this exception: 
Skip a.png due to an error:
CUDA out of memory. Tried to allocate 3.10 GiB (GPU 0; 8.00 GiB total capacity; 3.83 GiB already allocated; 2.17 GiB free; 4.40 GiB reserved in total by PyTorch).

Thanks in advance

**Comment by ilgrillo28** [comment] 2020-11-25 13:52
Me too.

**Comment by innat** [comment] 2020-11-25 17:34
This is because of the large input image. For example, if you have an image with `1k` by `1k`, it may throw OOM but if you resize it, let's say `512` by `512`, it won't skip that image.

**Comment by ilgrillo28** [comment] 2020-11-25 17:43
> 
> 
> This is because of the large input image. For example, if you have an image with `1k` by `1k`, it may throw OOM but if you resize it, let's say `512` by `512`, it won't skip that image.

Thanks, I'm sorry. I was too hasty. There were already explanation of this. Sorry again.

What I'm wondering is why on a **Surface Laptop 3 with Intel Iris GPU the .py tells me "CUDA out of memory"**, also indicating an amount of RAM available. 
Intel Iris does not support the CUDA API.

**Comment by innat** [comment] 2020-11-25 18:41
I don't understand your speech properly, but if things are all about facing the OOM error in your laptop, that's really sad but normal. The whole photo restoration is done during the internship (according to the author) and didn't focus to optimize it. Nevertheless, just to get started I would prefer to do inference on colab or kaggle platform.

**Comment by ilgrillo28** [comment] 2020-11-26 11:16
> I don't understand your speech properly, but if things are all about facing the OOM error in your laptop, that's really sad but normal. The whole photo restoration is done during the internship (according to the author) and didn't focus to optimize it. Nevertheless, just to get started I would prefer to do inference on colab or kaggle platform.

I don’t know what type of memory the stages are using. The GPU one or the system RAM?

**Comment by innat** [comment] 2020-11-26 18:02
It always GPU ran (VRAM).

**Comment by guoqc3** [comment] 2020-11-30 11:01
Does this mean that your laptop can only be repaired with small pictures?That's the same problem I'm facing now

**Comment by alessandro-lion** [comment] 2020-12-05 20:43
> Does this mean that your laptop can only be repaired with small pictures?That's the same problem I'm facing now

Running the software on Colab, which use a Google Virtual Server to execute it is also stopping on CUDA OOM while trying a small picture, aprox 1100x800 pixel. In terms of mobile phone camera nomenclature it means around 1Megapixel, that istance states to have 14Gb Vram. Probably we will see the same amount of VRAM on a notebook in 2030 maybe, so it looks like there is no way to work on something bigger than a thumbnail image on any system.

**Comment by zhangmozhe** [comment] 2021-02-04 06:43
Duplicate of https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/issues/19#issue-711976416

**Closed by zhangmozhe** 2021-02-04 06:43 UTC
