### ISSUE TITLE
Out of memory issue CPU(128GB RAM) mode as well as GPU mode (16GB)

### ISSUE THREAD

**Issue by nowfalsalahudeen** [microsoft/Bringing-Old-Photos-Back-to-Life#96] opened 2020-12-18 05:32 UTC
out of memory issue in cpu mode even in 128 gb RAM wasn't enough for signle 512 px image with --with_scratch method,
also in gpu mode same too
high can i optimize the memory usage?

**Comment by Thamjeedps** [comment] 2020-12-18 05:55
We are facing the same issue, Kindly help us to sort out the same...

**Comment by Pantich78** [comment] 2020-12-25 23:07
Hi there, I'm having the same issue using Colab.
Thanks

**Comment by dev-tty** [comment] 2020-12-27 01:33
I'm having the same issue on CPU - only very low resolution photos ware working / the included sample photos.

**Comment by codeandmedia** [comment] 2020-12-27 16:28
It looks weird, I tried to execute the script with GPU 0 or GPU -1 but anyway I got out of memory on Azure Standard_NC24 (48GB GPU)
```
python3 run.py --input_folder  /home/oldphoto/old/ --output_folder /home/oldphoto/new/ --GPU -1  --with_scratch
Running Stage 1: Overall restoration
initializing the dataloader
model weights loaded
directory of testing image: /home/oldphoto/old
processing f1149510480.jpg
Traceback (most recent call last):
  File "detection.py", line 155, in <module>
    main(config)
  File "detection.py", line 127, in main
    P = torch.sigmoid(model(scratch_image))
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/oldphoto/Bringing-Old-Photos-Back-to-Life/Global/detection_models/networks.py", line 119, in forward
    x = up(x, blocks[-i - 1])
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/oldphoto/Bringing-Old-Photos-Back-to-Life/Global/detection_models/networks.py", line 168, in forward
    out = self.conv_block(out)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/oldphoto/Bringing-Old-Photos-Back-to-Life/Global/detection_models/networks.py", line 140, in forward
    out = self.block(x)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/anaconda/envs/py37_default/lib/python3.7/site-packages/torch/nn/functional.py", line 2058, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 210.00 MiB (GPU 0; 11.17 GiB total capacity; 10.57 GiB already allocated; 122.44 MiB free; 10.67 GiB reserved in total by PyTorch)
You are using NL + Res
Finish Stage 1 ...


Running Stage 2: Face Detection
Traceback (most recent call last):
  File "run.py", line 107, in <module>
    detect_all_dlib(url=stage_2_input_dir, save_url=stage_2_output_dir)
NameError: name 'detect_all_dlib' is not defined`

```

```
oldphoto@oldphoto:~/Bringing-Old-Photos-Back-to-Life$ nvidia-smi
Sun Dec 27 16:27:14 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 455.32.00    Driver Version: 455.32.00    CUDA Version: 11.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000699:00:00.0 Off |                    0 |
| N/A   27C    P8    32W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           On   | 0000599E:00:00.0 Off |                    0 |
| N/A   27C    P8    31W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla K80           On   | 0000B8FC:00:00.0 Off |                    0 |
| N/A   32C    P8    27W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla K80           On   | 0000E4CE:00:00.0 Off |                    0 |
| N/A   33C    P8    27W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
oldphoto@oldphoto:~/Bringing-Old-Photos-Back-to-Life$
```

**Comment by zhangmozhe** [comment] 2021-02-04 06:28
Duplicate of https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/issues/19#issue-711976416. We will actively solve this out of memory issue.

**Closed by zhangmozhe** 2021-02-04 06:28 UTC

**Comment by elmout31** [comment] 2021-04-07 20:00
For GPU-1 which mean CPU only, it is not well supported by default (git clone of April 2021). (Help tell us to use only 0,1,2 as GPU option)
For the GPU -1, I have tried with a 1.3MB image and it work with the following modification inside Global/detection.py:
On line 97 add a else condition to the if config.GPU >= 0:
```
    else:
        model.to("cpu")
```
        
Around line 145 add a else condition on  if config.GPU >= 0:
```
else:
       scratch_image_scale = scratch_image_scale.to("cpu")
```

Once done, extend your swap file size. I extend it to 128GB. (use of swapoff/swapon., dd, mkswap.. on your favorite linux distribution ) 
Now the 1.3MB image with the --with_scratch work and consumed around 123GB of RAM. It is extremely slow, but it works great.
Regards

**Comment by dev-tty** [comment] 2021-04-08 04:41
> For GPU-1 which mean CPU only, it is not well supported by default (git clone of April 2021). (Help tell us to use only 0,1,2 as GPU option)
> For the GPU -1, I have tried with a 1.3MB image and it work with the following modification inside Global/detection.py:
> On line 97 add a else condition to the if config.GPU >= 0:
> 
> ```
>     else:
>         model.to("cpu")
> ```
> 
> Around line 145 add a else condition on if config.GPU >= 0:
> 
> ```
> else:
>        scratch_image_scale = scratch_image_scale.to("cpu")
> ```
> 
> Once done, extend your swap file size. I extend it to 128GB. (use of swapoff/swapon., dd, mkswap.. on your favorite linux distribution )
> Now the 1.3MB image with the --with_scratch work and consumed around 123GB of RAM. It is extremely slow, but it works great.
> Regards

I was looking for exactly this! Thanks so much!
